### ISSUE TITLE
Local import

### ISSUE THREAD

**Issue by szhang-ezypay** [Suruat/vue-2-crumbs#10]
Hi, is there a way to locally import the plugin instead of globally?

I tried to import it in my wrapper component but always getting 'Failed to mount component: template or render function not defined.'

```
<template>
  <app-breadcrumbs></app-breadcrumbs>
</template>

<script>
import Vue2Crumbs from 'vue-2-crumbs';

export default {
  name: 'MyBreadcrumb',
  components: { 'app-breadcrumbs': Vue2Crumbs },
};
</script>

```

**Comment by darkiron** [comment]
Is not a component but a plugin. Use doc process for install the plugin or import only `breadcrumbComponent.js`
