### ISSUE TITLE
add dynamic label in parent

### ISSUE THREAD

**Issue by darkiron** [Suruat/vue-2-crumbs#11]
Hi, 
How I cant add a Dynamic Label ? 
I try with : 
```
 breadcrumb () {
    return {
      label: 'Postuler',
      parent:  {
        name: 'offre-emploi',
        params: {
          id: this.$route.params.id,
          slug: this.$route.params.slug,
          location: this.$route.params.location
        },
        label: this.$store.state.offre.job_title
      }
    }
  },
```
label don't set with job_title.

**Comment by Suruat** [comment]
Hello!
Is it the last part of breadcrumb? Is there some error in console?

**Comment by darkiron** [comment]
not is parent. No error in console.

**Comment by Suruat** [comment]
> IMPORTANT! Because of the tech limitations, you need to be sure, that dynamic breadcrumb is the last one in the list. Plugin doesn't allowed to build breadcrumbs list with dynamic part in the middle of it. To handle this cases, please check using parentsList property.

Please, read [this block](https://github.com/Suruat/vue-2-crumbs#using-parentslist) of documentation.

**Comment by darkiron** [comment]
> > IMPORTANT! Because of the tech limitations, you need to be sure, that dynamic breadcrumb is the last one in the list. Plugin doesn't allowed to build breadcrumbs list with dynamic part in the middle of it. To handle this cases, please check using parentsList property.
> 
> Please, read [this block](https://github.com/Suruat/vue-2-crumbs#using-parentslist) of documentation.

Ok, I make some review, bug fix and code review ... 
I solved my issue,  
I think you can refactor and delete unused function and props. 

I need maybe with your help , to solve link building with params ..  

I hope your are ready ;)
