### ISSUE TITLE
How change template write crambs?

### ISSUE THREAD

**Issue by gladishukD** [Suruat/vue-2-crumbs#2]

**Comment by gladishukD** [comment]
How change template and add new atributs, because I need add attr itemscope for CEO.
Help me please!!!!!!

**Comment by Suruat** [comment]
Hi! Thank you for the question.
Unfortunately, current version hasn't support for changing template. But I will work on adding it to the next update. I will do my best for make it in near future.

**Comment by gladishukD** [comment]
The plugin is very good, thank you for the answer.
