### ISSUE TITLE
/src/index.js missing in git

### ISSUE THREAD

**Issue by luckydonald** [Suruat/vue-2-crumbs#9]
Hey, I fail to build this from source.
It seems like `/src/index.js`  is missing.

Apparently the `.gitignore`  entry 
```gitignore
index.js
```
also causes `/src/index.js` to not be included into git, and thus making building impossible.

To hide only the build output 
```gitignore
/index.js
```
 should only exclude the build output.

**Comment by Suruat** [comment]
Hi, @luckydonald !
Thanks for bringing this up! `/src/index.js` is added to repository
